### ISSUE TITLE
Kohana can not find swiftmailer file

### ISSUE THREAD

**Issue by dejwid** [shadowhand/email#40]
file: classes/Kohana/email.php
line: 451

this does not work:

    require Kohana::find_file('vendor/swiftmailer', 'swiftmailer/lib/swift_required');

but this (as a replacment) works correctly:

    require 'vendor/swiftmailer/swiftmailer/lib/swift_required.php';

**Comment by tomaszzelcer79** [comment]
#40

**Comment by piotrgolasz** [comment]
@shadowhand the path in the file is missing one "/swiftmailer".
Take a look at https://github.com/piotrgolasz/email/commit/f7b1a971d62e1f29899817ddd4c6b9e3ff8cb690

**Comment by shadowhand** [comment]
People really should just be using Swiftmailer directly at this point...
