### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by Sajgoniarz** [shadowhand/email#42]
Hi, im using utf-8 but in raw message I still get something like "Otrzyma=C5=82e=C5=9B" instead of "Otrzymałeś" and in email client all " are predicted with "3D" i tried to setEncoder(Swift_Encoding::get8BitEncoding()); in constructor and few another places, but still with no luck, how to set encoding right?

**Comment by shadowhand** [comment]
This module is no longer maintained. Feel free to fork.
