### ISSUE TITLE
Swiftmailer update please

### ISSUE THREAD

**Issue by krassswr** [shadowhand/email#44]
Hello, I know that this module is old, but it would be nice if you can update swiftmailer to version 5.4.4 because of php7 support.

**Comment by shadowhand** [comment]
PR welcome.

**Comment by krassswr** [comment]
Hello, I have performed some tests and here is what I see.
Version of module with swiftmailer v. 4.0.4 works with PHP 7.0.13
Version of module with swiftmailer v. 4.3 is not working with PHP 7.0.13
Version of module with swiftmailer v. 5.4.4 works with PHP 7.0.13
So I think that it is possible to just update swiftmailer to 5.4.4 with no other changes, or write a comment to old version that is using 4.0.4 that it can work with PHP 7.

**Comment by shadowhand** [comment]
@krassswr is the API for 5.4 the same as 4.0?

**Comment by krassswr** [comment]
I don't know for sure, but I used last version of your module which came with swiftmailer v 4.3 and replace content of vendor directory with swiftmailer 5.4.4 and then send mail ... mail was received and no errors in logs was found.

**Comment by yakatz** [comment]
There aren't that many differences, and these appear to be the major ones:
- License changed from LGPL to MIT
- `Swift_SignedMessage` has been removed
- They recommend not using `MailTransport`

None of the functions called by this package appear to have changed in a way that would break it.

https://github.com/swiftmailer/swiftmailer/compare/ae540bed1079c07aa12e9e62d9d8d4fc49bbdff2...5.x

**Comment by shadowhand** [comment]
Anyone is free to fork this package. I will am no longer going to maintain it.
