### ISSUE TITLE
Message order

### ISSUE THREAD

**Issue by yakatz** [shadowhand/email#45]
There is an open bug against SwiftMailer (https://github.com/swiftmailer/swiftmailer/issues/184 and https://github.com/swiftmailer/swiftmailer/issues/56) where `multipart/alternative` messages don't always show up properly if the plain text is added first.

https://github.com/shadowhand/email/blob/e42cef439635dcba6dacf3516d853f164a2bfcc5/classes/Kohana/Email.php#L173 currently forces that bug.

I am guessing there was a reason that it is set that way, so without knowing the reason, I am not sure of the best fix.

**Comment by shadowhand** [comment]
This module is no longer maintained. Feel free to fork.
